name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client
      run: cd client && cargo build --verbose
    - name: Test client
      run: cd client && cargo test --verbose
    - name: Build server
      run: cd server && cargo build --verbose
    - name: Test server
      run: cd server && cargo test --verbose
