name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Change Directory to client
      run: cd client
    - name: Build client
      run: cargo build --verbose
    - name: Test client
      run: cargo test --verbose
    - name: Change Directory to server
      run: cd ../server
    - name: Build server
      run: cargo build --verbose
    - name: Test server
      run: cargo test --verbose
